version: '2'

services:
  challenge:
    image: ${CI_REGISTRY_IMAGE}/challenge
    labels:
      io.rancher.container.pull_image: always
    ports:
      - "3000:3000"
    expose:
      - 3000
    restart: always
